spring.application.name=backend
#informaç~eos 
# informações sobre o Bando de Dados [Entrega 3]
spring.jpa.database= postgresql
spring.datasource.url=jdbc:postgresql://localhost:5432/saep_db2
spring.datasource.username=postgres
spring.datasource.password=postgres

# jpa - automacao da criacao das tabelas do BD
spring.jpa.hibernate.ddl-auto=update
# mostra o sql no terminal
spring.jpa.show-sql=true
# utilização de termos especificos do PostgresSql para otimizar consultas
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
